freifunk-berlin/firmware-packages

utils/luci-app-owm/luasrc/owm.lua
See https://github.com/freifunk-berlin/firmware/issues/206 .
This patch is intended to prevent owm.lua from pushing information about a) private encrypted wifi networks and b) the local WAN port configuration to the public.
Ultimatively, I think there should be a user-configurable whitelist instead of a blacklist, and some "show me what information gets published beforehand" functionality, but this is way too much effort with libremap coming.
=> Exclude encrypted/wan interfaces in OWM info

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/generalInfo.lua, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/decide.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/reboot.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/apinfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/generalInfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/ipinfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/meshipinfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/shareBandwidth.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/vpninfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/welcome.htm
Fixed typos. Removed outdated info (link to Heise netmask calculator - config.berlin does this). Moved some info boxes (the one on the contact form was located below the map and easily overlooked). Clarified data privacy. Switched wording to that used in the config.berlin info mail ("DHCP-Network"). Better descriptions on "decide" page.
No functional changes.
=> cosmetic changes

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/shareInternet.lua
Before this change we copied the key/cert files from the upload directory to the
/etc/openvpn directory. This results in a waste of disk space. If we use move
instead we do not keep redundant information on disk and save some space.
Thanks to Patrick Grimm for pointing this out.
=> [ffwizard-berlin] use move instead of copy after upload of key/cert

utils/freifunk-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
We use the ula prefix of the router to "calculate" the ip of the router.
Addresses: https://github.com/freifunk-berlin/firmware/issues/166
=> [dhcp-defaults] add an ipv6 dns entry for frei.funk

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults
Restart luci_statistics every 30 minutes to deallocate all memory.
=> [statistics-defaults] hotfix collect memory leak

utils/freifunk-berlin-migration/Makefile
freifunk-berlin-migration depends on 'semver', which doesn't exist
and is packages by itself (see files).
=> [freifunk-berlin-migration]: remove dependency on semver

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults
This is supposed to remove the noop line put into crontab by the 0.1.0 migration and insert a working command. Also, reloading every 15 minutes as at least some WR1043 seem not to last even 30 minutes. Do not merge yet, will do more testing.
=> Fix collectd memory leak hotfix

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua, utils/luci-app-owm/Makefile
1. The Assistent doesn't really depend on luci-mod-freifunk apart from patching into its menu entry. This removes the dependency: On small routers, luci-mod-freifunk can then be omitted.
2. sysupgrade copies all files in /etc/config to the overlay during the upgrade. Change migration to delete any duplicated files; this saves a dozen or so kb typically. Note: Patching sysupgrade itself would be better from a space-preserving perspective (as currently, the overlay has to hold the duplicate files briefly), but it would change the upgrate semantics from "keep config as-is" to "update any non-modified config files to ROM default".
=> Changes to support routers with 4MB flash

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults
Both olsrd-txtinfo and collectd-olsrd default to port 2006; this changes our config to that default. http://www.olsr.org/?q=txtinfo_plugin https://collectd.org/wiki/index.php/Plugin:olsrd
This fixes https://github.com/freifunk-berlin/firmware/issues/218 . Do we need migration?
=> [olsrd-defaults] set txtinfo port to 2006 (default)

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn
This fixes problems with providers using DS-Lite and should reduce fragmentation on server side.
This adresses https://github.com/freifunk-berlin/firmware/issues/226 as well as parts of the OpenVPN server discussion.
=> [freifunk-berlin-openvpn] [migration] set OpenVPN mssfix default to 1300

utils/freifunk-berlin-uhttpd-defaults/uci-defaults/freifunk-berlin-uhttpd-defaults
The assumption is that the forced redirect is irritating for the average users
because the self signed certificate is not trusted by the browser. The user has
to add the certificate by hand. We assume that is to much for the average user.
=> [uhttpd-defaults]: do not force a redirect to https

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults
We change the dns entry for the ping plugin to a more flexible dns entry. At the
moment the entry only points to a ipv4 address.
Addresses: https://github.com/freifunk-berlin/firmware/issues/253
TODO:
=> [ff-berlin-statistics-defaults]: change ping host for collectd

utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/decide.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/ipinfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/meshipinfo.htm, utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/vpninfo.htm
remove all reverence to ask for VPN-key on the mailinglist and reference the new ca.berlin.freifunk.net page
=> update links to new VPN-request webtool

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/ffwizard.lua
this fixes https://github.com/freifunk-berlin/firmware/issues/257
=> [ffwizard] [migration] use ffvpn for QoS rather than wan

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-openvpn-files/openvpn/60-ffopenvpn
- fixes syntax error in migration-script
- stops openvpn to crash on startup with "file not found"
=> openvpn-script "ffvpn-up.sh" changed in #a63a603 to /lib/freifunk/

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
"limit"-option has to be 3 addresses less than the network-size
(network-, broadcast-, router-address)
=> [ffwizard] correcting dhcp-limit

utils/luci-app-owm/Makefile, utils/luci-app-owm/files/owm.lua, utils/luci-app-owm/luasrc/owm.lua
when the latitude/longitude are not defined for the node, /usr/sbin/owm.lua tries to update the map anyway. such updates get refused by OWM-server 
> fail   Doc  Statuscode: 403 http://api.openwifimap.net//update_node/Ahof-frieden03.olsr ({"error":"forbidden","reason":"Document must have a longitude"}
)
so prevent script from running without the informations, which also saves a lot of processing time
<pre>
root@Ahof-frieden03:~# time /tmp/owm.lua
fail   Doc  Statuscode: 403 http://api.openwifimap.net//update_node/Ahof-frieden03.olsr ({"error":"forbidden","reason":"Document must have a longitude"}
)
real    0m 4.10s
user    0m 0.47s
sys     0m 0.13s
root@Ahof-frieden03:~# time /tmp/owm.lua 
real    0m 0.26s
user    0m 0.23s
sys     0m 0.03s
</pre>
code works on my node
=> do not update OWM without latitude/longitude defined

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/generalInfo.lua
- this removes the uci-setting "system.system.latlon"
- "latlon" seems to be only historic, also by checking the whole src-tree (relevant for Freifunk) there seems to be no active use of the parameter; only found some fallback in case "system.system.latitude" and "system.system.longitude" are not defined
- code seems to work fine on my systems
- this closes https://github.com/freifunk-berlin/firmware/issues/307
- is a resubmit of PR #61 
- is in public beta in all unstable-firmware images of https://github.com/freifunk-berlin/firmware/tree/unstable_SAm0815 without any known problems
=> remove "latlon" from uci: system.system (resend)

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh
in addition to the https://github.com/freifunk-berlin/firmware-packages/pull/68 which became https://github.com/freifunk-berlin/firmware-packages/commit/cd4d319499338ff5b088a441acaed1847ea34d5c
we changed this th ffwizard, but forgot about a migration for this
=> migration: add migration for removal of dhcp.lan config

utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh
found that on a fresh install the migration-script gets started, when working on 
- https://github.com/freifunk-berlin/firmware-packages/pull/72
- https://github.com/freifunk-berlin/firmware-packages/pull/73
This is caused by the fact that UCI "system.version" in not defined and the default "0.0.0" is choosen.
Running migraition on fresh installs makes no sense and has the chance to break some settings.
This idea here, tries to find the difference between a fresh install (of a >= kathleen 0.2.0) firmware and running on a old firmware by looking for files older than the first kathleen-release. See "ctime" of file /tmp/timestamp for this (Line34).
Only the "basic" Semver numbers are taken into account when deciding on migration-steps. The current code as some problems with the …
=> Fixes running migration even on fresh install

utils/freifunk-berlin-openvpn-files/openvpn/60-ffopenvpn, utils/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn
- in recent OpenWRT CC the OpenVPN is run via procd
- using this daemon seems more reliable in case if OpenVPN-crashes
- using the default init-script also allows using default UCI-config
- also implements the nice idea binding to the WAN-interface to prevent OpenVPN over freifunk-mesh, and gets rid of using firewall-rules for blocking this traffic
also takes care of https://github.com/freifunk-berlin/firmware/issues/338
=> extend "openvpn hotplug" to run via procd

utils/freifunk-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults, utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-openvpn-files/Makefile, utils/freifunk-berlin-openvpn-files/openvpn/60-ffopenvpn, utils/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/ffwizard.lua
This moves starting OpenVPN to a hotplug script.
Discussion: https://github.com/freifunk-berlin/firmware/issues/272
This removes the "block VPN03 IPs in firewall to prevent the always-running OpenVPN process from connecting to VPN03 via mesh" hack.
It directly launches OpenVPN in the ifup script but leaves the user the option to use UCI OpenVPN settings. This is probably unnecessary - nobody is really using UCI to configure OpenVPN - and the upcoming rewritten wizard will support standard OpenVPN config files as they are supplied by commercial OpenVPN providers.
Also, a hidden dependency on iptables is removed; fw3 does handling of the tnl interfaces here.
Probably procd should be used instead of directly launching OpenVPN. Someone else up to implementing this?
=> Start OpenVPN via hotplug script

utils/luci-app-owm/Makefile, utils/luci-app-owm/luasrc/owm.lua
This code implements a compatible json-dataset to send Router-model and Chipset-type as in kathleen 0.1.2. 
So the statistics-wegpage will work as it is (see issue https://github.com/freifunk-berlin/firmware/issues/378#issuecomment-237082534).
You can copy the owm.lua to the router under /usr/lib/lua/luci to for direct testing
=> Fix/owm stats for kathleen 0.2.0

utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh, utils/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults
see
https://lists.berlin.freifunk.net/pipermail/berlin/2016-November/034556.html
We should fix this in any case (even if we use procd instead of ffwatchd) because it's a config bug anyways.
=> [olsrd-defaults] fix filename of olsr6 watchdog file

utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh
This sets the OWM API URL to a Berlin specific one so we can have
some features like encrypted mail addresses, automated contact
forms, other map data formats, other backend databases etc.
easily without having to update all clients later.
Setting owm_api in the profile is better than changing the default
in owm.lua since the latter would (in the long run) break OWM for
other communities using Kathleen.
=> [migration] update OWM API URL

utils/collectd-snmp-templates/Makefile, utils/freifunk-berlin-dhcp-defaults/Makefile, utils/freifunk-berlin-firewall-defaults/Makefile, utils/freifunk-berlin-freifunk-defaults/Makefile, utils/freifunk-berlin-lib-guard/Makefile, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-network-defaults/Makefile, utils/freifunk-berlin-olsrd-defaults/Makefile, utils/freifunk-berlin-openvpn-files/Makefile, utils/freifunk-berlin-statistics-defaults/Makefile, utils/freifunk-berlin-uhttpd-defaults/Makefile, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-owm/Makefile, utils/luci-mod-freifunk-ui/Makefile
all our packages are only scripts (shell or lua) / just datafiles which do not depend on a specific CPU-arch. 
This changes makes them cross-installable on all archs and even currently unsupported archs.
build this locally and works as before. Hope to get it into kathleen-0.2.0 as there is no functional change.
=> make all packages arch independent

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
Hey, I added support to read out the wirless channel from the community profile for the luci-app-ffwizard-berlin. So it is not hardcoded to 13 and 36.
=> added support for reading wifi channel from community profile

utils/luci-app-owm/Makefile, utils/luci-app-owm/luasrc/owm.lua
currently the complete release-name is send in field firmware.release only
("firmware":{"name":"","revision":"Freifunk Berlin kathleen 0.1.2"}). With
new OpenWrt 15.05 / LuCI automatically the revision is added to this.
this makes sorting / grouping by relase difficult and requires some
extra steps on client-side.
This change corrects the datafields as follows:
"firmware":{"name":"Freifunk Berlin kathleen 0.2.0","revision":"git affe"}
- "name" is DISTRIB_ID + DISTRIB_CODENAME + DISTRIB_RELEASE
- "revision" is DISTRIB_REVISION
- use owm.get_version in place of luci.version
- rely on "/etc/openwrt_release" as original luci.version
=> owm: send release-name in field firmware.name

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/shareInternet.lua
LuCI-upload directory changed from /lib/uci/upload to /etc/luci-uploads in upstream 
(modules/luci-base: Move LuCI FileUpload directory to /etc/luci-uploads and save across sysupgrade)
fixes https://github.com/freifunk-berlin/firmware/issues/421
tested with build http://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx-generic/160/default/freifunk-berlin-1.0.0-olsrd0903-alpha-49489be-gl-ar150-sysupgrade.bin
please wait for merge till after 0.3.0 release
=> ffwizard: switch to new path of upload-dir

defaults/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults, utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh
If we don't set the IpVersion explicitly to 6 the startup of the daemon
fails because the IPv4 version of the txtinfo and jsoninfo plugin tries
to listen on 0::. If we don't set the IpVersion we start the IPv4
version of olsrd.
Fixes issue https://github.com/freifunk-berlin/firmware/issues/443
=> freifunk-berlin-olsrd-defaults: explicitly set IpVersion to 6 for olsrd6

utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua
there seems to be no reason to do this (anymore).
This code is there since initial commit of ffwizard, but no comment for what reason
see https://github.com/freifunk-berlin/firmware/issues/344
=> ffwizard: don't create cronjob to restart "wan"

defaults/freifunk-berlin-firewall-defaults/Makefile, defaults/freifunk-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/firewall.lua
as the upstream-traffic of nodes with a uplink is no traffic like inside the freifunk-network, it should be considered as different from "pure freifunk".
This also supports https://github.com/freifunk-berlin/firmware/issues/416 and PR #120
=> add separate firewall-zone "ffvpn"

defaults/freifunk-berlin-firewall-defaults/Makefile, defaults/freifunk-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults, defaults/freifunk-berlin-network-defaults/Makefile, defaults/freifunk-berlin-network-defaults/uci-defaults/freifunk-berlin-network-defaults, defaults/freifunk-berlin-openvpn-files/Makefile, defaults/freifunk-berlin-openvpn-files/openvpn/60-ffopenvpn, defaults/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn, defaults/freifunk-berlin-statistics-defaults/Makefile, defaults/freifunk-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults, defaults/freifunk-berlin-uplink-tunnelberlin-files/Makefile, defaults/freifunk-berlin-uplink-tunnelberlin-files/uci-defaults/freifunk-berlin-tunnelberlin-openvpn, defaults/freifunk-berlin-uplink-vpn03-files/Makefile, defaults/freifunk-berlin-uplink-vpn03-files/uci-defaults/freifunk-berlin-vpn03, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/shareInternet.lua, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/ffwizard.lua, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/olsr.lua
This renames the current interface used to provide an uplink from "ffvpn" to "ffuplink", as discussed in https://github.com/freifunk-berlin/firmware/issues/472.
* Interface "WAN" becomes a bridge, to give other interfaces a way to connect to them.
* rename the interface in related default-scripts
* rename OpenVPN-certificates to "ffuplink.*" (OpenVPN-config + wizard)
* add a migration for this
=> provide common interface for uplink-traffic

defaults/freifunk-berlin-system-defaults/Makefile, defaults/freifunk-berlin-system-defaults/uci-defaults/freifunk-berlin-system-defaults, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua
* change the default hostname of unconfigured systems
----
PR123
* do not push a default-gw to the dhcp-clients on an unconfigured router
* this prevents multihomed-clients to have to default-gw whenn configuring the router initially (this router will probably have no uplink at this time)
* as the "LAN"-interface config will be deleted and replaced by "DHCP" there should be no problem after later setup (ffwizzard); backbone-images need to take care if they reuse the "LAN"-interface
=> change default hostname of unconfigured systems

defaults/freifunk-berlin-dhcp-defaults/Makefile, defaults/freifunk-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
By default we will not announce ourself as default-gw to the clients, to prevent them sending us packets to forward, but not being configured yet.
So the client can be connected to his fully working network (via WiFI) and connect to us for configuration (via LAN), without breaking it's current connection.
As we do this on "LAN"-interface, which will be deleted by the wizard this will not cause problems on regular installs. Only systems configured by hand and keeping the LAN-interface, have to take care.
=> don't announce as default-gw during initial setup

defaults/freifunk-berlin-network-defaults/Makefile, defaults/freifunk-berlin-network-defaults/hotplug.d/iface/60-ffuplink_policyrouting, defaults/freifunk-berlin-network-defaults/uci-defaults/freifunk-berlin-network-defaults, defaults/freifunk-berlin-network-defaults/uci-defaults/freifunk-berlin-network-ip-route, defaults/freifunk-berlin-openvpn-files/Makefile, defaults/freifunk-berlin-openvpn-files/files/ffberlin-uplink, defaults/freifunk-berlin-openvpn-files/openvpn/ffvpn-up.sh, defaults/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn, defaults/freifunk-berlin-uplink-no-tunnel/Makefile, defaults/freifunk-berlin-uplink-no-tunnel/files/60-ffuplink, defaults/freifunk-berlin-uplink-no-tunnel/files/ffberlin-uplink, defaults/freifunk-berlin-uplink-no-tunnel/uci-defaults/freifunk-berlin-notunnel, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/shareInternet.lua
add a package to use the wan-connection directly (w/o VPN)
=> add ffuplink-package to use the routers-wan connection

addons/collectd-addons/Makefile
Builds are broken currently because old URL is invalid now.
=> collectd-addons: fix ubnt mibs url

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/shareInternet.lua, utils/luci-mod-freifunk-ui/Makefile, utils/luci-mod-freifunk-ui/luasrc/view/freifunk/index.htm
due to some change in upstream projects the sites "shareInternet" and
"index" stopped working throwing an error
> A runtime error occured:
/usr/lib/lua/luci/model/uci.lua:157: attempt to call method 'get_all' (a
nil value)
Looks like we have to call get() like a method. Still i dont know why it did work before.
=> Fix index and shareInternet page.

defaults/freifunk-berlin-openvpn-files/Makefile, defaults/freifunk-berlin-openvpn-files/files/ffberlin-uplink, defaults/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-openvpn, uplinks/freifunk-berlin-uplink-no-tunnel/Makefile, uplinks/freifunk-berlin-uplink-no-tunnel/files/ffberlin-uplink, uplinks/freifunk-berlin-uplink-no-tunnel/uci-defaults/freifunk-berlin-notunnel, uplinks/freifunk-berlin-uplink-tunnelberlin-files/Makefile, uplinks/freifunk-berlin-uplink-tunnelberlin-files/uci-defaults/freifunk-berlin-tunnelberlin-openvpn, uplinks/freifunk-berlin-uplink-vpn03-files/Makefile, uplinks/freifunk-berlin-uplink-vpn03-files/uci-defaults/freifunk-berlin-vpn03, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
This provides the migration steps to upgrade from Kathleen 0.3.0 to Hedy 1.0.0 and creates a Hedy 1.0.1.
Beside upgrading our settings, there is also a step "r1_0_0_upstream()" (https://github.com/freifunk-berlin/firmware-packages/commit/46ca9b5803df412ed595bef975a3e1c6f26e581b) which updates some files that are purely upstream and never touched by us.
With this PR we also get a UCI-value (ffberlin-uplink.preset.current) for the uplink-preset that was used last time. this can be used to determine, if the preset has been changed during the upgrade, to select the proper uplink-preset for the next time or an auto-upgrader.
=> Migration for v1.0.1

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
Avoids running into a lua error when leaving the "Mesh-IP" entry empty.
https://github.com/freifunk-berlin/firmware/issues/531
=> Wizard: Check for empty Mesh-IP

uplinks/freifunk-berlin-uplink-no-tunnel/uci-defaults/freifunk-berlin-notunnel, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
use the functions provided by OpenWrt to format the address and set to "LAA"-bit.
* was tested in an separate script 
* looks more elegant than the loop before
=> uplink-notunnel: simplify creation of static macaddress

defaults/freifunk-berlin-openvpn-files/openvpn/60-ffopenvpn
Declarations of variables outside of a function result in the script silently failing.  All such variable declarations have been removed.
=> hotplug 60-ffopenvpn: remove local declaration of variables

utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
The uci:get function needs a key of type string. Therefore we convert
the channel from int to string before using it as argument for uci:get.
This fixes https://github.com/freifunk-berlin/firmware/issues/593
=> luci-app-ffwizard-berlin: convert channel to string for uci:get

defaults/freifunk-berlin-olsrd-defaults/Makefile, defaults/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/freifunk-berlin-wizard-backend/Makefile, utils/freifunk-berlin-wizard-backend/files/usr/lib/ffwizard.d/20-network.sh, utils/freifunk-berlin-wizard-backend/files/usr/lib/ffwizard.d/30-olsrd.sh
This PR is in conjunction with PR https://github.com/openwrt/luci/pull/2200.
Nameserver 80.67.169.40 is provided by the French Data Network (www.fdn.fr/actions/dns)
The relevant Freifunk Issues are https://github.com/freifunk-berlin/firmware/issues/551 and https://github.com/freifunk-berlin/firmware/issues/552
=> update the nameservers used in the firmware

addons/freifunk-berlin-bbbdigger/Makefile, addons/freifunk-berlin-bbbdigger/files/postinst.sh
The server has been changed from an IP address to a fully qualified domain name (a.bbb-vpn.berlin.freifunk.net).  Additionally a second FQDN has been added which currently does not resolve (b.bbb-vpn.berlin.freifunk.net).  The unresolvable domain name does not cause any performance issues but does result in a few warnings in the log.
=> bbbdigger: change server IP address to FQDN

utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
the generated MAC-address must be stored by uci
Or is it done in some other place?
=> migration: fix setting a static MAC-address

utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/olsr.lua, utils/luci-mod-freifunk-ui/luasrc/view/freifunk-map/frame.htm, utils/luci-mod-freifunk-ui/luasrc/view/freifunk-map/map.htm
The version number for OLSR library plugins is not longer needed and
in many cases out of date.  This commit completes changes in
ba58e285d56f975ab6f0fad4a01a434408cacfef
5364b36f5f11cc1253258cb162767d0c52124e3c
The upstream commit which caused these changes is
https://github.com/openwrt-routing/packages/commit/f4bc87dc65729ef663f6dc9b7e157a909c5eb92b
I have compiled with these changes but I don't know what to test for.  There is another PR for luci by @booo. 
This fixes the issue in https://github.com/freifunk-berlin/firmware/issues/605
This PR is also related to  https://github.com/freifunk-berlin/firmware/issues/594
=> update files which reference OLSR library plugins by version number

utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
Set the dns entry on the loopback interface. We set it on the loopback
interface so we only have one entry for the whole network configuration.
=> luci-app-ffwizard-berlin: set dns entry on loopback interface

uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/uci-defaults/freifunk-berlin-z95_tunnelberlin-tunneldigger
As we don't need any authentication for the tunneldigger uplink, set "ffberlin-uplink.uplink.auth=none"
With this setting the wizard will not ask for x509 certs.
=> uplink tunnel-berlin: set auth-type for tunneldigger

uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/uci-defaults/freifunk-berlin-z95_tunnelberlin-tunneldigger
this implements https://github.com/freifunk-berlin/firmware-packages/pull/147 and creates a correct U/L-bit
@pmelange this is the commit removed from https://github.com/freifunk-berlin/firmware-packages/pull/154 - feel free to merge anytime
=> uplink tunneldigger: change macaddr generation into a for-loop

utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
fix version number to call notunnel_ffuplink_ipXtable
add migration for notunnel macaddr
resolves https://github.com/freifunk-berlin/firmware-packages/pull/162#issuecomment-445558738
=> For hedy 1.0.x notunnel migration

addons/freifunk-berlin-bbbdigger/Makefile, addons/freifunk-berlin-bbbdigger/files/postinst.sh, addons/freifunk-berlin-tunneldigger/Makefile, addons/freifunk-berlin-tunneldigger/files/config.default, addons/freifunk-berlin-tunneldigger/files/tunneldigger.hotplug, addons/freifunk-berlin-tunneldigger/files/tunneldigger.init, uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/Makefile, uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/uci-defaults/freifunk-berlin-z95_tunnelberlin-tunneldigger
Create the freifunk-berlin-tunneldigger package
This package is based on the gluon tunneldigger package.
https://github.com/freifunk-gluon/packages/tree/master/net/tunneldigger
The source for the tunneldigger client is at
https://github.com/wlanslovenija/tunneldigger
The differences to the gluon version are:
* The init script is disabled by default
* Fixed problems with starting multiple tunneldigger instances
* Added a hotplug script which waits for the bind_interface to go up/down before starting/stopping any associated tunneldigger
* Does not start tunneldigger for an interface if the interface is disabled
* Does not start tunneldigger if it has already been started
* Removes pid files when tunneldigger is stopped
Additionally all changes to uplink-tunnelberlin-tunneldigger and …
=> Create a tunneldigger package for freifunk-berlin

utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh, utils/freifunk-berlin-migration/uci-defaults/zz_freifunk-berlin-migration-clean_jffs.sh
move the clean up of possible duplicates of rom-files into a separate uci-default script, which will run as very last.
This prevents from problems caused by https://github.com/freifunk-berlin/firmware/issues/641, but keeps this functionality.
This was initially tested on the Hedy-1.0.x branch
=> migration: run jffs-cleanup as very last uci-default script

defaults/freifunk-berlin-olsrd-defaults/Makefile, defaults/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
the OLSR daemon in the 1.0.x firmware dumps a core whenever it
crashes.  This can slowly kill a router as it runs out of memory.  For the
1.0.x firmwares, the function r1_0_2_add_olsrd_garbage_collection has been
added
the OLSR daemon for the 1.1.x firmware does not have this issue.  For 1.1.x
firwares, the function r1_1_0_remove_olsrd_garbage_collection to undo the
garbage collection.
The garbage collection is done as a cron job which runs daily at 00:00
0 0 * * *	rm -f /tmp/olsrd*core
This addresses issue https://github.com/freifunk-berlin/firmware/issues/642
=> add OLSRd core dump garbage collectiong

defaults/freifunk-berlin-openvpn-files/Makefile, defaults/freifunk-berlin-openvpn-files/uci-defaults/freifunk-berlin-z90_openvpn, uplinks/freifunk-berlin-uplink-no-tunnel/Makefile, uplinks/freifunk-berlin-uplink-no-tunnel/uci-defaults/freifunk-berlin-z95_notunnel, uplinks/freifunk-berlin-uplink-tunnelberlin-files/Makefile, uplinks/freifunk-berlin-uplink-tunnelberlin-files/uci-defaults/freifunk-berlin-z95_tunnelberlin-openvpn, uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/Makefile, uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files/uci-defaults/freifunk-berlin-z95_tunnelberlin-tunneldigger, uplinks/freifunk-berlin-uplink-vpn03-files/Makefile, uplinks/freifunk-berlin-uplink-vpn03-files/uci-defaults/freifunk-berlin-z95_vpn03
This adds the code, which handles changing the uplink-preset.
It's done by comparing the "ffberlin-uplink.preset.current" with the definition in the currently installed preset. The UCI-value can be:
* the preset used before this image was installed
* value "undefined" when no preset was setup ever, normally a fresh install
When a real preset-change is detected the function "create_ffuplink()" is called to reinit the ffuplink-settings to factory-defaults.
=> implement "changing uplink"

utils/luci-app-owm/Makefile
all functions are also in luci-lib-ip. it is included by luci-mod-network --> luci-base
see pr https://github.com/openwrt/luci/pull/2507 on luci
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>
=> luci-app-owm: rm luci-lib-luaneightbl DEPENDS.

utils/luci-app-ffwizard-berlin/Makefile
as luci-mod-admin-full depends on luci-base (https://github.com/openwrt/luci/blob/openwrt-18.06/modules/luci-mod-admin-full/Makefile#L10) we can drop this dependency.
=> ffwizard: remove direct dependency to luci-base

defaults/freifunk-berlin-network-defaults/Makefile, defaults/freifunk-berlin-network-defaults/pingcheck/offline.d/60-freifunk-wan, defaults/freifunk-berlin-network-defaults/pingcheck/online.d/60-freifunk-wan, defaults/freifunk-berlin-network-defaults/uci-defaults/freifunk-berlin-pingcheck-defaults, uplinks/freifunk-berlin-uplink-no-tunnel/Makefile, uplinks/freifunk-berlin-uplink-no-tunnel/files/etc/pingcheck/offline.d/60-freifunk-notunnel, uplinks/freifunk-berlin-uplink-no-tunnel/files/etc/pingcheck/online.d/60-freifunk-notunnel
When the wan interface looses internet connectivity, The no-tunnel uplink does not go down automatically.  Additionally, and locally generated traffic will still continue to use the wan interface (dnsmasq, statistics, ping).
uplink no-tunnel:
The scripts, when installed with pingcheck, will take down or up the ffuplink interface when the internet is not reachable via the wan interface.
The pingcheck package is now a dependency of freifunk-berlin-uplink-no-tunnel
network-defaults:
The scripts, when installed with pingcheck, will set routing rules for locally generated traffic depending on if the wan interface has connectivity to the internet.  When the wan interface looses connectivity, new ip rules are put in place to put the olsr-tunnel and olsr-default tables with a higher priority than …
=> add pingcheck monitoring for the wan interface

defaults/freifunk-berlin-olsrd-defaults/Makefile, defaults/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults, utils/freifunk-berlin-migration/Makefile, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
olsrd defaults: update to use the new digitalcourage nameservers
migration: update to new digitalcourage nameservers
The old digitalcourage nameserver 85.214.20.141 will be retired in 2020. The new nameserver id 46.182.19.48.  This commit updates the list of nodes to ping in the OLSRd defaults.
The change is announced https://digitalcourage.de/support/zensurfreier-dns-server
This fixes https://github.com/freifunk-berlin/firmware/issues/682
=> defaults and migration: update to new digitalcourage nameservers

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
The settings used by the wizard are mostly set in ```/etc/config/freifunk`` and optionally overridden in the community profile.  Commit b0545ac creates the ```'80211s'``` defaults section in ```/etc/config/freifunk```.  Any profiles which would like to override the default (such as the mesh_id) need to make commits to the pofiles in Luci.
The default options are
```
uci set freifunk.80211s=defaults
uci set freifunk.80211s.mode='mesh'
uci set freifunk.80211s.encryption='none'
uci set freifunk.80211s.mesh_id='Mesh-Freifunk'
uci set freifunk.80211s.mesh_fwding='0'
uci set profile_berlin.80211s=defaults
uci set profile_berlin.80211s.mesh_id="Mesh-Freifunk-Berlin"
```
The user can select between the new default 802.11s mode and the legacy adhoc mode.  To make it possible to know the difference …
```
=> Add 802.11s support to the wizard

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-mod-freifunk-ui/Makefile
**Do not merge before the firmware is based off of OpenWRT 19.x**
This is specific for the luci-master branch
This became an issue because the luci-lib-ipkg code has been
removed from luci-base.  The upstream commit is
https://github.com/openwrt/luci/commit/4bbe32548c407ec6ae104934b3f1fe53539de9f6
=> Openwrt 19x: luci-master: add new dependency to luci-lib-ipkg

addons/freifunk-berlin-bbbdigger/Makefile
OLSRv1 is the spoken protocol on the BBB-VPN, so olsrd is a logical dependency.
=> bbbdigger: depend on olsrd

defaults/freifunk-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
As per RFC4039:
In some environments, such as those in which high mobility occurs and
the network attachment point changes frequently, it is beneficial to
rapidly configure clients.  And, in these environments it is possible
to more quickly configure clients because the protections offered by
the normal (and longer) 4-message exchange may not be needed.  The
4-message exchange allows for redundancy (multiple DHCP servers)
without wasting addresses, as addresses are only provisionally
assigned to a client until the client chooses and requests one of the
provisionally assigned addresses.  The 2-message exchange may
therefore be used when only one server is present or when addresses
are plentiful and having multiple servers commit addresses for a
client is not a problem.
The DHCP-v4 …
=> dhcp-defaults: enable DHCP-rapid commit by default

defaults/freifunk-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
**What is the problem?**
syslog is spammed by: daemon.warn dnsmasq-dhcp: DHCP packet received on xxx_wan which has no address
**What is the expected behaviour?**
dnsmasq should not care / be silent for 'br-wan ffuplink_wan'
fixes freifunk-berlin/firmware#837
=> dnsmasq ignore br-wan ffuplink_wan

utils/luci-app-ffwizard-berlin/luasrc/view/freifunk/assistent/snippets/generalInfo.htm
* add hint to insert contact-link from registration-wizard
* add hint for automatically generated nodename if not supplied by user
A lot of new nodes do not supply a contact-info. Add a hint that also http-links will be accepted. This is esp. relevant for the contactlink generated by the IP-registration.
So we hopefully decrease the number of "uncontactable" nodes again.
=> Wizard: update test for general-Info snippet

addons/collectd-addons/files/collectd-snmp/ubnt-airmax.conf
* sysUpTimeInstance is measured in 100/second
* scale it down to more meaningful days of uptime (as it's done for collectd-uptime by default)
=> collectd-addons/snmp: scale uptime to days

defaults/freifunk-berlin-system-defaults/uci-defaults/freifunk-berlin-system-defaults, utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Define a uci "system.was_development" flag, which signals, that the node has ran development code once. This flag might be useful to signal that the system might have conflicting settings, due to an specific development-branch. 
A development-branch might define a setting, which is different in the final release, but can potentially cause malfunction. As of our long release-pauses also regular users have to use development-firmware, to support their hardware (a.t.m. >100 such nodes online). 
Very likely many of these users run such firmware, as it's their only option. When a release will be ready, these people very likely just upgrade to this release. I don't know if there is a specific version around where this will cause problems, now or even in a further release.
As a simple example I …
=> define an internal "Non release flag" 

addons/collectd-addons/files/collectd-snmp/ubnt-airmax.conf
Running SNMP-Monitoring of a NanoBeam AC (http://monitor.berlin.freifunk.net/host.php?h=Verklaerung-core&p=snmp) shows that some labels are wrong / misleading, so fix this.
* change rx-power to rx-level
* suffix tx-power by unit "dBm"
=> addons/snmp: correct some labels for Ubiquiti AirMax

addons/freifunk-berlin-lua-tools/Makefile, addons/freifunk-berlin-lua-tools/luasrc/tools/freifunk/freifunk-berlin.lua, utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/generalInfo.lua, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/olsr.lua, utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/tools.lua
Move some generic code from the assistent into this new common package.
This way the functions can be used by other code as well.
=> add new package "freifunk-berlin-lua-tools"

utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua
I found this fix some time ago and forgot about it, as I use the wizard only rarely. 
Use nil instead of "", as caption for the individual pages of the wizard. The interpretation by LuCI seems to have changed by the rework in 19.07 to the JS-based model.
fixes https://github.com/freifunk-berlin/firmware/issues/801
=> wizard: fix showing empty tabs on top of app

addons/freifunk-berlin-tunneldigger/Makefile
port of https://github.com/freifunk-gluon/packages/commit/3822f44013ccf60729d66c6143f554b6db2ccb63 based on
https://github.com/freifunk-gluon/packages/issues/242.
So applies to us in the same way.
=> tunneldigger: remove unneeded kmod-l2tp-ip dependency

defaults/freifunk-berlin-network-defaults/root/etc/uci-defaults/freifunk-berlin-network-defaults, uplinks/freifunk-berlin-uplink-notunnel/root/etc/uci-defaults/freifunk-berlin-z95_notunnel, utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/wireless.lua
Adapt our network-setup to OpenWrts change of the way bridges are defined from OpenWrt-21.02.0-rc2 onwards. (See: openwrt/openwrt@892fc7c)
This applies to "network-defaults" and "uplink-notunnel" for br-wan, "wizard" for br-dhcp. 
Tested the on a WDR3600, <strike>a test on a WDR-4900 (or any other device having a MAC-address defined) will be really great (fd3390a39623e48aa4fe24bb56a3bacb4e729497)</strike>.
=> adapt network-configuration to changed UCI-syntax

utils/luci-app-ffwizard-berlin/Makefile, utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua, utils/luci-app-ffwizard-berlin/root/etc/uci-defaults/wizarddefaults
The luci-mod-freifunk has the new feature to redirect to a custom page when LuCI is called without an explicit page (https://github.com/freifunk/openwrt-packages/commit/21e69cd27d736f13295e2af79108617ccc694b45). Let's use this to redirect to the wizard and remove the redirection again when the wizard has finished.
This way we don't need the "redirect on firstboot" patch (up to Kathleen 0.1.2) and can also drop our forked "luci-mod-freifunk-ui" package, which is basically the same package with the mentioned patch included.
=> use "redirect_landingurl" feature of mod-freifunk to bring up wizard on 1st-boot
